name: msk_utils
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  package_info: ^0.4.0+16
  
  sprintf: ^4.0.2
  sentry: ^3.0.1
  device_info: 0.4.2+4
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  dio: ^3.0.9
  intl: ^0.16.1
  flutter_mobx: ^0.3.3+3
  mobx: ^0.3.9+3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.3
  mobx_codegen: ^0.3.10+1
  
  
  
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: br.com.msk.msk_utils
        pluginClass: MskUtilsPlugin
      ios:
        pluginClass: MskUtilsPlugin
      macos:
        pluginClass: MskUtilsPlugin

        
scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean