name: msk_utils
description: Flutter utility package, with utilities for navigation, databases, and extensions for strings, maps, lists and more
version: 1.0.6
repository: https://github.com/ReniDelonzek/msk_utils

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  package_info_plus: ^4.0.2

  sprintf: ^7.0.0
  sentry: ^7.7.0
  device_info_plus: ^9.0.2
  path_provider: ^2.0.15
  hive: ^2.2.3
  dio: ^5.2.0+1
  intl: ^0.18.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.5
  mobx_codegen: ^2.3.0

  flutter_test:
    sdk: flutter

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
