name: msk_utils
description: Flutter utility package, with utilities for navigation, databases, and extensions for strings, maps, lists and more
version: 0.0.4
repository: https://github.com/ReniDelonzek/msk_utils

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  package_info: ^0.4.1
  sprintf: ^4.0.2
  sentry: ^3.0.1
  device_info: ^1.0.0
  path_provider: ^2.0.1
  hive: ^1.4.1+1
  dio: ^3.0.9
  intl: ^0.17.0
  mobx: ^1.1.0
  flutter_mobx: ^1.1.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.3
  mobx_codegen: ^1.1.2
  
  flutter_test:
    sdk: flutter
        
scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean
