name: msk_utils
description: Flutter utility package, with utilities for navigation, databases, and extensions for strings, maps, lists and more
version: 1.0.5
repository: https://github.com/ReniDelonzek/msk_utils

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  package_info_plus: ^2.0.0
  
  sprintf: ^7.0.0
  sentry: ^6.2.2
  device_info_plus: ^6.0.0
  path_provider: ^2.0.2
  hive: ^2.0.4
  dio: ^4.0.0
  intl: ^0.17.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.6
  mobx_codegen: ^2.0.1+3
  
  
  
  flutter_test:
    sdk: flutter
        
scripts:
   build: flutter pub run build_runner build --delete-conflicting-outputs
   watch: flutter pub run build_runner watch --delete-conflicting-outputs
   clean: flutter pub run build_runner clean
